<template>
  <div class="app-container">
    <el-alert title="内容页用于邀请函、通知、参会须知、长图和资料。发布首页前，入口只能引用已发布的内容。" type="info" :closable="false" class="mb16" />
    <el-form :model="query" inline><el-form-item><el-input v-model="query.title" placeholder="标题" clearable @keyup.enter="getList" /></el-form-item><el-form-item><el-select v-model="query.status" clearable placeholder="状态" style="width: 120px"><el-option label="草稿" value="draft" /><el-option label="已发布" value="published" /><el-option label="已归档" value="archived" /></el-select></el-form-item><el-form-item><el-button type="primary" @click="getList">查询</el-button><el-button type="primary" plain @click="add">新增内容</el-button><el-button type="danger" plain :disabled="!selection.length" @click="remove()">删除</el-button></el-form-item></el-form>
    <el-table :data="rows" v-loading="loading" @selection-change="selection = $event"><el-table-column type="selection" width="55" /><el-table-column prop="title" label="标题" min-width="220" /><el-table-column prop="visibility" label="可见范围" width="110" /><el-table-column prop="status" label="状态" width="110" /><el-table-column prop="validStart" label="生效开始" width="180" /><el-table-column label="操作" width="180" fixed="right"><template #default="scope"><el-button link type="primary" @click="edit(scope.row)">编辑</el-button><el-button link type="primary" @click="attachments(scope.row)">资料</el-button><el-button link type="danger" @click="remove(scope.row)">删除</el-button></template></el-table-column></el-table>
    <pagination v-show="total > 0" :total="total" v-model:page="query.pageNum" v-model:limit="query.pageSize" @pagination="getList" />
    <el-dialog v-model="editorOpen" :title="form.contentId ? '编辑内容' : '新增内容'" width="920px" class="meeting-form-dialog" append-to-body destroy-on-close><el-form ref="formRef" :model="form" :rules="rules" label-width="90px"><el-row :gutter="16"><el-col :span="16"><el-form-item label="标题" prop="title"><el-input v-model="form.title" maxlength="200" /></el-form-item></el-col><el-col :span="8"><el-form-item label="排序"><el-input-number v-model="form.sortOrder" :min="0" /></el-form-item></el-col><el-col :span="12"><el-form-item label="可见范围"><el-select v-model="form.visibility"><el-option label="公开" value="public" /><el-option label="登录可见" value="login" /><el-option label="报名后可见" value="registered" /></el-select></el-form-item></el-col><el-col :span="12"><el-form-item label="状态"><el-select v-model="form.status"><el-option label="草稿" value="draft" /><el-option label="已发布" value="published" /><el-option label="已归档" value="archived" /></el-select></el-form-item></el-col><el-col :span="24"><el-form-item label="摘要"><el-input v-model="form.summary" type="textarea" :rows="2" maxlength="1000" /></el-form-item></el-col><el-col :span="24"><el-form-item label="封面"><material-select v-model="form.coverUrl" :show-tip="false" /></el-form-item></el-col><el-col :span="12"><el-form-item label="生效开始"><el-date-picker v-model="form.validStart" type="datetime" value-format="YYYY-MM-DD HH:mm:ss" /></el-form-item></el-col><el-col :span="12"><el-form-item label="生效结束"><el-date-picker v-model="form.validEnd" type="datetime" value-format="YYYY-MM-DD HH:mm:ss" /></el-form-item></el-col><el-col :span="24"><el-form-item label="正文"><editor v-model="form.contentHtml" :min-height="360" /></el-form-item></el-col></el-row></el-form><template #footer><el-button type="primary" @click="submit">保存</el-button><el-button @click="editorOpen=false">取消</el-button></template></el-dialog>
    <el-dialog v-model="attachmentsOpen" title="内容资料" width="760px" append-to-body><el-button type="primary" plain class="mb12" @click="newAttachment">新增资料</el-button><el-table :data="attachmentRows"><el-table-column prop="fileName" label="文件名" /><el-table-column prop="visibility" label="可见范围" width="110" /><el-table-column prop="status" label="状态" width="90" /><el-table-column label="操作" width="120"><template #default="scope"><el-button link type="primary" @click="editAttachment(scope.row)">编辑</el-button><el-button link type="danger" @click="deleteAttachment(scope.row)">删除</el-button></template></el-table-column></el-table></el-dialog>
    <el-dialog v-model="attachmentOpen" :title="attachment.attachmentId ? '编辑资料' : '新增资料'" width="620px" class="meeting-form-dialog" append-to-body><el-form :model="attachment" label-width="90px"><el-form-item label="文件名"><el-input v-model="attachment.fileName" /></el-form-item><el-form-item label="文件地址"><el-input v-model="attachment.fileUrl" placeholder="上传后的受控地址" /></el-form-item><el-form-item label="文件类型"><el-input v-model="attachment.fileType" placeholder="pdf/docx" /></el-form-item><el-form-item label="可见范围"><el-select v-model="attachment.visibility"><el-option label="公开" value="public" /><el-option label="登录可见" value="login" /><el-option label="报名后可见" value="registered" /></el-select></el-form-item><el-form-item label="状态"><el-switch v-model="attachment.status" active-value="1" inactive-value="0" /></el-form-item></el-form><template #footer><el-button type="primary" @click="submitAttachment">保存</el-button><el-button @click="attachmentOpen=false">取消</el-button></template></el-dialog>
  </div>
</template>

<script setup name="MeetingContent">
import { computed, getCurrentInstance, onMounted, ref } from 'vue'
import { useRoute } from 'vue-router'
import MaterialSelect from '@/components/MaterialSelect'
import { addMeetingContent, deleteContentAttachments, deleteMeetingContent, getMeetingContent, listContentAttachments, listMeetingContent, saveContentAttachment, updateMeetingContent } from '@/api/meeting/content'
const { proxy } = getCurrentInstance(); const route = useRoute(); const activityId = computed(() => Number(route.query.id)); const loading = ref(false); const rows = ref([]); const total = ref(0); const selection = ref([]); const query = ref({ pageNum: 1, pageSize: 10, activityId: undefined, title: undefined, status: undefined }); const editorOpen = ref(false); const formRef = ref(); const form = ref({}); const rules = { title: [{ required: true, message: '请输入标题', trigger: 'blur' }] }; const attachmentsOpen = ref(false); const attachmentOpen = ref(false); const attachmentRows = ref([]); const attachment = ref({}); const contentId = ref(null)
function getList() { loading.value = true; query.value.activityId = activityId.value; listMeetingContent(query.value).then(res => { rows.value = res.rows || []; total.value = res.total || 0 }).finally(() => { loading.value = false }) }
function reset() { form.value = { contentId: undefined, activityId: activityId.value, title: '', summary: '', contentHtml: '', coverUrl: '', visibility: 'public', status: 'draft', validStart: null, validEnd: null, sortOrder: 0 } }
function add() { reset(); editorOpen.value = true }
function edit(row) { getMeetingContent(row.contentId).then(res => { form.value = res.data || {}; editorOpen.value = true }) }
function submit() { formRef.value.validate(valid => { if (!valid) return; const request = form.value.contentId ? updateMeetingContent(form.value) : addMeetingContent(form.value); request.then(() => { proxy.$modal.msgSuccess('保存成功'); editorOpen.value = false; getList() }) }) }
function remove(row) { const ids = row?.contentId || selection.value.map(item => item.contentId); proxy.$modal.confirm('确认删除选中内容？').then(() => deleteMeetingContent(ids)).then(() => { proxy.$modal.msgSuccess('删除成功'); getList() }).catch(() => {}) }
function attachments(row) { contentId.value = row.contentId; listContentAttachments(contentId.value).then(res => { attachmentRows.value = res.data || []; attachmentsOpen.value = true }) }
function newAttachment() { attachment.value = { contentId: contentId.value, fileName: '', fileUrl: '', fileType: '', visibility: 'public', status: '1', sortOrder: 0 }; attachmentOpen.value = true }
function editAttachment(row) { attachment.value = { ...row }; attachmentOpen.value = true }
function submitAttachment() { saveContentAttachment(attachment.value).then(() => { proxy.$modal.msgSuccess('保存成功'); attachmentOpen.value = false; listContentAttachments(contentId.value).then(res => { attachmentRows.value = res.data || [] }) }) }
function deleteAttachment(row) { proxy.$modal.confirm('确认删除资料？').then(() => deleteContentAttachments(row.attachmentId)).then(() => { attachmentRows.value = attachmentRows.value.filter(item => item.attachmentId !== row.attachmentId); proxy.$modal.msgSuccess('删除成功') }).catch(() => {}) }
onMounted(() => { if (!activityId.value) return proxy.$modal.msgError('缺少会议ID'); getList() })
</script>
