package com.ruoyi.system.service.impl;
import java.util.ArrayList; import java.util.Date; import java.util.HashMap; import java.util.List; import java.util.Map;
import org.jsoup.Jsoup; import org.jsoup.safety.Safelist; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.stereotype.Service;
import com.ruoyi.common.core.domain.model.MpLoginUser; import com.ruoyi.common.exception.ServiceException; import com.ruoyi.common.utils.StringUtils; import com.ruoyi.system.domain.YcApplyOrder; import com.ruoyi.system.domain.YcMeetingNotice; import com.ruoyi.system.mapper.YcApplyOrderMapper; import com.ruoyi.system.mapper.YcMeetingNoticeMapper; import com.ruoyi.system.service.IYcMeetingNoticeService;
@Service public class YcMeetingNoticeServiceImpl implements IYcMeetingNoticeService {
 @Autowired private YcMeetingNoticeMapper mapper; @Autowired private YcApplyOrderMapper orderMapper;
 public List<YcMeetingNotice> list(YcMeetingNotice query){return mapper.selectList(query);}
 public int save(YcMeetingNotice notice){ if(notice==null||notice.getActivityId()==null||StringUtils.isEmpty(notice.getTitle()))throw new ServiceException("activityId and title required"); if(StringUtils.isEmpty(notice.getPriority()))notice.setPriority("normal"); if(StringUtils.isEmpty(notice.getVisibility()))notice.setVisibility("public"); if(StringUtils.isEmpty(notice.getStatus()))notice.setStatus("draft"); if("published".equals(notice.getStatus())&&notice.getPublishTime()==null)notice.setPublishTime(new Date()); notice.setContentHtml(Jsoup.clean(notice.getContentHtml()==null?"":notice.getContentHtml(), Safelist.relaxed())); return notice.getNoticeId()==null?mapper.insert(notice):mapper.update(notice); }
 public Map<String,Object> publicList(Long activityId,MpLoginUser user){ YcMeetingNotice q=new YcMeetingNotice();q.setActivityId(activityId);q.setStatus("published");List<Map<String,Object>> rows=new ArrayList<>();for(YcMeetingNotice n:mapper.selectList(q)){if(!visible(n,user))continue;Map<String,Object> v=new HashMap<>();v.put("noticeId",n.getNoticeId());v.put("title",n.getTitle());v.put("priority",n.getPriority());v.put("publishTime",n.getPublishTime());v.put("read",user!=null&&user.getUserId()!=null&&mapper.hasRead(n.getNoticeId(),user.getUserId()));rows.add(v);}Map<String,Object> out=new HashMap<>();out.put("notices",rows);return out; }
 public Map<String,Object> detail(Long activityId,Long noticeId,MpLoginUser user){YcMeetingNotice n=mapper.selectById(noticeId);if(n==null||!activityId.equals(n.getActivityId())||!visible(n,user))throw new ServiceException("notice not available");if(user!=null&&user.getUserId()!=null)mapper.markRead(noticeId,user.getUserId());Map<String,Object> v=new HashMap<>();v.put("noticeId",n.getNoticeId());v.put("title",n.getTitle());v.put("priority",n.getPriority());v.put("contentHtml",Jsoup.clean(n.getContentHtml()==null?"":n.getContentHtml(),Safelist.relaxed()));v.put("publishTime",n.getPublishTime());return v;}
 private boolean visible(YcMeetingNotice n,MpLoginUser user){if(n.getPublishTime()!=null&&new Date().before(n.getPublishTime())||(n.getValidEnd()!=null&&new Date().after(n.getValidEnd())))return false;if("public".equals(n.getVisibility()))return true;if(user==null||user.getUserId()==null)return false;if("login".equals(n.getVisibility()))return true;List<YcApplyOrder> orders=orderMapper.selectPortalUserOrders(n.getActivityId(),user.getOpenid(),user.getPhone(),"0");return "registered".equals(n.getVisibility())&&orders!=null&&!orders.isEmpty();}
}
